import { cookieStorage, createStorage, http } from 'wagmi'
import { WagmiAdapter } from '@reown/appkit-adapter-wagmi'
import { avalancheFuji, avalanche } from '@reown/appkit/networks'
import type { Chain } from 'viem'
import { AVALANCHE_FUJI_CONFIG } from 'x402-sf'

// Read Project ID from environment variables
export const projectId = process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID

// Ensure Project ID is defined at build time
if (!projectId) {
  throw new Error('Missing required environment variable: NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID. Get one at https://cloud.reown.com')
}

// Define supported networks - using Avalanche for our Superfluid integration
export const networks: [Chain, ...Chain[]] = [avalancheFuji as unknown as Chain]

// Create the Wagmi adapter instance
export const wagmiAdapter = new WagmiAdapter({
  storage: createStorage({ storage: cookieStorage }),
  ssr: true,
  projectId: projectId || '',
  networks,
  // Use Superfluid's RPC instead of the public default (which rate-limits / 429s).
  transports: {
    [avalancheFuji.id]: http(AVALANCHE_FUJI_CONFIG.chain.rpcUrl),
  },
})

// Export the Wagmi config generated by the adapter
export const config = wagmiAdapter.wagmiConfig
